config/routes.rb
TumblrClone::Application.routes.draw do
  root to: redirect('/dashboard')
  
  get 'password-reset-new', to: 'sessions#password_reset_new', as: 'password_reset_new'
  post 'password-reset-send', to: 'sessions#password_reset_send', as: 'password_reset_send'
  get 'password-reset-edit/:id', to: 'sessions#password_reset_edit', as: 'password_reset_edit'
  post 'password_reset_update/:id', to: 'sessions#password_reset_update', as: 'password_reset_update'
  get 'login', to: 'sessions#new', as: 'login'
  post 'signin', to: 'sessions#create', as: 'signin'
  get 'signout', to: 'sessions#destroy', as: 'signout'
  match '/auth/facebook/callback', to: 'sessions#facebook_signin'
  match '/auth/failure', to: 'sessions#new'
  get 'facebook-destroy', to: 'sessions#facebook_destroy', as: 'facebook_destroy'
  
  resources :users, only: [:new, :create, :show, :update, :destroy]
  get 'dashboard', to: 'users#show', as: 'home'
  get 'findblogs', to: 'users#findblogs', as: 'findblogs'
  get 'settings', to: 'users#edit', as: 'settings'
  get 'users/:id/public', to: 'users#public', as: 'public'
  post 'avatarchange', to: 'users#avatarchange', as: 'avatarchange'
  match '/faq', to: 'users#faq'
  post 'search', to: 'users#search', as: 'search'
  
  resources :posts, except: [:show]
  get 'drafts', to: 'posts#drafts', as: 'drafts'
  get 'posts/:id/publish', to: 'posts#publish', as: 'publish'
  post 'sms_post', to: 'posts#sms_post', as: 'sms_post'
  get 'preview/:id', to: 'posts#preview', as: 'preview'
  
  resources :activs, only: [:index]
  
  get 'followers', to: 'followings#followers', as: 'followers'
  get 'following', to: 'followings#following', as: 'following'
  post 'follow',   to: 'followings#create',    as: 'follow'
  post 'unfollow', to: 'followings#destroy',   as: 'unfollow'
  
  get  'likes',  to: 'likes#index',   as: 'likes'
  post 'like',   to: 'likes#create',  as: 'like'
  post 'unlike', to: 'likes#destroy', as: 'unlike'
end

app/models/following.rb
# == Schema Information
#
# Table name: followings
#
#  id          :integer          not null, primary key
#  follower_id :integer
#  followed_id :integer
#  created_at  :datetime         not null
#  updated_at  :datetime         not null
#

class Following < ActiveRecord::Base
  attr_accessible :followed_id, :follower_id
  
  belongs_to :follower, class_name: "User"
  belongs_to :followed, class_name: "User"
end

app/controllers/followings_controller.rb
class FollowingsController < ApplicationController
  before_filter :require_current_user!
  before_filter :get_menu_stats
  
  def followers
    @followings = current_user.following_users
    @followers  = current_user.followers_users
  end
  
  def following
    @following = current_user.following_users.includes(:posts)
  end
  
  def create
    follower_id = params[:follower_id]
    following = Following.new({follower_id: current_user.id,
                               followed_id: follower_id})
    user = User.find(follower_id).username
    
    if following.save
      Activ.create({sent_user_id: current_user.id, got_title: "#{current_user.username} started following you", got_user_id: follower_id})
      
      if request.xhr?
        render text: "Started following \"#{user}\""
      else
        flash[:main] = "You started following \"#{user}\""
        (params[:back].nil?) ? (redirect_to root_url) : (redirect_to params[:back])
      end
      
    else
      flash[:main] = "Error in trying to follow \"#{user}\""
      (params[:back].nil?) ? (redirect_to root_url) : (redirect_to params[:back])
    end
    
  end
  
  def destroy
    if params[:follower_id]
      following = Following.where("follower_id=? AND followed_id=?", params[:follower_id], current_user.id).first
    else
      following = Following.where("follower_id=? AND followed_id=?", current_user.id, params[:followed_id]).first
    end
    
    if following.destroy
      
      if request.xhr?
        render text: "Removed from the following list"
      else
        flash[:main] = "Removed from the following list"
        (params[:back].nil?) ? (redirect_to root_url) : (redirect_to params[:back])        
      end
      
    else
      flash[:main] = "Error in trying to unfollow"
      (params[:back].nil?) ? (redirect_to root_url) : (redirect_to params[:back])
    end
    
  end
end

app/helpers/followings_helper.rb
module FollowingsHelper
end

app/views/followings/followers.html.erb
<% unless @followers.empty? %>
	<div id="white_pane">
		<div class="title_and_controls"><%= pluralize(@followers.count, 'person') %> <%= @followers.count == 1 ? "follows" : "follow" %> you</div>

	
		<ul>
			<% @followers.each_with_index do |follower, i| %>
				<li class="following_list_items<%= " follower_list_darker_bg" if i%2 != 0 %>" data-id="<%= follower.id %>">
					
					<div class="float_left">
						<a href="<%= public_url(follower.id) %>">
							<%= image_tag follower.avatar.url(:small), class: "avatar_40 float_left" %>
						</a>
						
						<div class="float_left" style="margin-left: 12px;">
							<a href="<%= public_url(follower.id) %>">
								<div class="following_username"><%= follower.username %></div>
							</a>

							<!-- IGNORE LINK -->
							<form action="<%= unfollow_url %>" method="post" data-id="<%= follower.id %>" class="list_ignore_link">
								<input type="hidden" name="authenticity_token" value="<%= form_authenticity_token %>">
								<input type="hidden" name="follower_id" value="<%= follower.id %>">
								<input type="hidden" name="back" value="<%= request.url %>">
								<input class="input_to_link ignore_link" type="submit" value="ignore">
							</form>
							
						</div>
					</div>
					

					<div class="float_right">
						<% unless @followings.include?(follower) %>
						
								<!-- FOLLOW BUTTON -->
								<form action="<%= follow_url %>" method="post" style="line-height: 40px" data-id="<%= follower.id %>" class="blue_follow_button">
									<input type="hidden" name="authenticity_token" value="<%= form_authenticity_token %>">
									<input type="hidden" name="follower_id" value="<%= follower.id %>">
									<input type="hidden" name="back" value="<%= request.url %>">
									<input class="button_follow_blue_big" type="submit" value="Follow">
								</form>
								
						<% end %>
					</div>

				</li>
			<% end %>
		</ul>
</div>
<% end %>

<% if @followers.empty? %>
	<div id="full_empty_page_anime">
		<div class="center">
		<div class="center_empty_page">
			<div class="empty_page_house relative"><div class="spinner"></div></div>
		</div>
		<div class="empty_page_shadow"></div>
		<div class="empty_page_text">There is no activity <br>on this page</div>
	</div>
	</div>
<% end %>

app/views/followings/following.html.erb
<% unless @following.empty? %>
<div id="white_pane">
	<div class="title_and_controls">Following <%= pluralize(@following.count, 'blog') %></div>


		<ul>
			<% @following.each_with_index do |following, i| %>
				<li class="following_list_items<%= " follower_list_darker_bg" if i%2 != 0 %>" data-id="<%= following.id %>">
					
					<div class="float_left">
						<a href="<%= public_url(following.id) %>">
							<%= image_tag following.avatar.url(:small), class: "avatar_40 float_left" %>
						</a>
						
						<div class="float_left" style="margin-left: 12px;">
							<a href="<%= public_url(following.id) %>">
								<div class="following_username"><%= following.username %></div>
							</a>
							<% if following.posts.last %>
								<div class="updated_info">
									Updated <%= time_ago_in_words(following.posts.last.created_at) %> ago
								</div>
							<% end %>
						</div>
						
					</div>
					

					<div class="float_right">
							<form action="<%= unfollow_url %>" method="post" style="line-height: 40px" data-id="<%= following.id %>" class="white_list_unfollow_button">
								<input type="hidden" name="authenticity_token" value="<%= form_authenticity_token %>">
								<input type="hidden" name="followed_id" value="<%= following.id %>">
								<input type="hidden" name="back" value="<%= request.url %>">
								<input class="button_unfollow_big" type="submit" value="Unfollow">
							</form>
					</div>

				</li>
			<% end %>
		</ul>
</div>
<% end %>

<% if @following.empty? %>
	<div id="full_empty_page_anime">
		<div class="center">
		<div class="center_empty_page">
			<div class="empty_page_house relative"><div class="spinner"></div></div>
		</div>
		<div class="empty_page_shadow"></div>
		<div class="empty_page_text">There is no activity <br>on this page</div>
	</div>
	</div>
<% end %>