config/routes.rb
TumblrClone::Application.routes.draw do
  root to: redirect('/dashboard')
  
  get 'password-reset-new', to: 'sessions#password_reset_new', as: 'password_reset_new'
  post 'password-reset-send', to: 'sessions#password_reset_send', as: 'password_reset_send'
  get 'password-reset-edit/:id', to: 'sessions#password_reset_edit', as: 'password_reset_edit'
  post 'password_reset_update/:id', to: 'sessions#password_reset_update', as: 'password_reset_update'
  get 'login', to: 'sessions#new', as: 'login'
  post 'signin', to: 'sessions#create', as: 'signin'
  get 'signout', to: 'sessions#destroy', as: 'signout'
  match '/auth/facebook/callback', to: 'sessions#facebook_signin'
  match '/auth/failure', to: 'sessions#new'
  get 'facebook-destroy', to: 'sessions#facebook_destroy', as: 'facebook_destroy'
  
  resources :users, only: [:new, :create, :show, :update, :destroy]
  get 'dashboard', to: 'users#show', as: 'home'
  get 'findblogs', to: 'users#findblogs', as: 'findblogs'
  get 'settings', to: 'users#edit', as: 'settings'
  get 'users/:id/public', to: 'users#public', as: 'public'
  post 'avatarchange', to: 'users#avatarchange', as: 'avatarchange'
  match '/faq', to: 'users#faq'
  post 'search', to: 'users#search', as: 'search'
  
  resources :posts, except: [:show]
  get 'drafts', to: 'posts#drafts', as: 'drafts'
  get 'posts/:id/publish', to: 'posts#publish', as: 'publish'
  post 'sms_post', to: 'posts#sms_post', as: 'sms_post'
  get 'preview/:id', to: 'posts#preview', as: 'preview'
  
  resources :activs, only: [:index]
  
  get 'followers', to: 'followings#followers', as: 'followers'
  get 'following', to: 'followings#following', as: 'following'
  post 'follow',   to: 'followings#create',    as: 'follow'
  post 'unfollow', to: 'followings#destroy',   as: 'unfollow'
  
  get  'likes',  to: 'likes#index',   as: 'likes'
  post 'like',   to: 'likes#create',  as: 'like'
  post 'unlike', to: 'likes#destroy', as: 'unlike'
end

app/models/post.rb
# == Schema Information
#
# Table name: posts
#
#  id         :integer          not null, primary key
#  title      :string(255)
#  body       :text
#  draft      :boolean          default(FALSE)
#  user_id    :integer
#  created_at :datetime         not null
#  updated_at :datetime         not null
#

class Post < ActiveRecord::Base
  attr_accessible :body, :draft, :title, :user_id
  
  validates :title, :body, presence: true
  validates :title, length: 1..45
  
  belongs_to :user
  has_many :likes, dependent: :destroy
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_filter :require_current_user!, except: [:sms_post]
  before_filter :get_menu_stats, except: [:publish, :sms_post]
  
  def index
    @posts = current_user.posts.where(draft: false).order("created_at DESC")
  end
  
  def drafts
    @posts = current_user.posts.where(draft: true).order("created_at DESC")
  end
  
  def new
    @post = Post.new
  end
  
  def create
    @post = current_user.posts.new(params[:post])
    @referer = params[:back]
    
    if @post.save
      flash[:main] = "Your post has been saved"
      (params[:back].nil?) ? (redirect_to root_url) : (redirect_to params[:back])
    else
      flash.now[:errors] = @post.errors.messages
      render :new      
    end
  end
  
  def edit
    @post = current_user.posts.find(params[:id])
  end
  
  def update
    @post = current_user.posts.find(params[:id])
    @post.draft = false unless params[:post][:draft]
    @referer = params[:back]
    
    if @post.update_attributes(params[:post])
      flash[:main] = "Your post has been updated"
      (params[:back].nil?) ? (redirect_to root_url) : (redirect_to params[:back])
    else
      flash.now[:errors] = @post.errors.messages
      render :edit
    end
  end
  
  def destroy
    post = current_user.posts.find(params[:id])
    
    if post.destroy
      
      if request.xhr?
        render text: "Your post has been deleted"
      else
        flash[:main] = "Your post has been deleted"
        (params[:back].nil?) ? (redirect_to root_url) : (redirect_to params[:back])
      end
      
    else
      flash[:main] = "There was an error in deleting your post"
      (params[:back].nil?) ? (redirect_to root_url) : (redirect_to params[:back])
    end
  end
  
  def publish
    draft = current_user.posts.where(draft: true).find(params[:id])
    
    if draft.update_attributes({draft: false})
      
      if request.xhr?
        render text: "Published"
      else
        flash[:main] = "Your draft has been published"
        redirect_to request.referer
      end

    else
      flash[:main] = "There was an error in trying to publish your draft"
      redirect_to request.referer
    end
  end
  
  def sms_post
    user = User.find_by_phonenumber(params["From"])
    
    if user
      Post.create!({body: params["Body"], title: "Sms Post", draft: false, user_id: user.id})
      
      to = params['From']
      body = 'Your post has been successfully posted'
      send_sms(to, body)
    end
    
    render :head
  end
  
  def preview
    # ONLY FOR AJAX REQUESTS
    user = User.find(params[:id])
    posts = user.posts.order("created_at DESC").limit(3)
    render json: posts
  end
end

app/views/posts/_new_post_menu.html.erb
<div class="relative">
	<a href="<%= public_url(current_user.id) %>">
		<div class="post_avatar_top relative">
			<%= image_tag current_user.avatar.url(:small) %>
			<div class="selector_left">
			</div>
		</div>
	</a>
</div>

<div class="new_post_menu">
	<ul>
		<a href="<%= new_post_url %>" id="new_post_text_form">
			<li style="border-left:0; margin-left:6px; opacity:1;">
				<div class="relative"><img src="/assets/top_text.png"></div>
				Text
			</li>
		</a>
		
		<li>
			<div class="relative"><img src="/assets/top_photo.png"></div>
			Photo
		</li>
		
		<li>
			<div class="relative"><img src="/assets/top_quote.png"></div>
			Quote
		</li>
		
		<li>
			<div class="relative"><img src="/assets/top_link.png"></div>
			Link
		</li>
		
		<li>
			<div class="relative"><img src="/assets/top_chat.png"></div>
			Chat
		</li>
		
		<li>
			<div class="relative"><img src="/assets/top_audio.png"></div>
			Audio
		</li>
		
		<li>
			<div class="relative"><img src="/assets/top_video.png"></div>
			Video
		</li>
	</ul>
	
	<div id="insert_here_new_form"></div>
</div>

app/views/posts/_post_items.html.erb
<% if @posts %>
	<ul>
		<% @posts.each_with_index do |post, i| %>
			<li class="<%= i==0 ? "first_post" : "post" %> full_post_block" data-id="<%= post.id %>">
				
				<!-- POST AVATAR -->
				<div class="relative">
					<a href="<%= public_url(post.user.id) %>">
						<div class="hover_over_content hidden" data-id="<%= post.user.id %>"></div>
						<div class="post_avatar" data-id="<%= post.id %>">
							<%= image_tag post.user.avatar.url(:small) %>
							<div class="selector_left">			
							</div>
						</div>
					</a>
				</div>
				
				<div class="full_post_content" data-id="<%= post.id %>">
				
				<!-- POST INFO -->
				<div class="post_username">
					<a href="<%= public_url(post.user.id) %>"><%= post.user.username %></a>
				</div>
				<div class="post_title">
					<%= post.title %><br>
				</div>
				<div class="post_body">
					<% body = post.body.gsub(/\r\n/, "<br>") %>
					<%= sanitize body, :tags => %w(strong b i br img) %>
				</div>
				
				
				<div class="post_footer">
					<div class="post_footer_flash" data-id="<%= post.id %>"></div>
					<div class="float_right">
						
						<% if post.user != current_user %>
						
							<% if @liked_posts && @liked_posts.include?(post.id) %>
								<% red_heart = "" %>
								<% grey_heart = " hidden" %>
							<% else %>
								<% red_heart = " hidden" %>
								<% grey_heart = "" %>
							<% end %>
								
								<!-- UNLIKE BUTTON -->
								<div class="float_left">
									<form action="<%= unlike_url %>" method="post" data-id="<%= post.id %>" class="red_like_button<%= red_heart %>">
										<input type="hidden" name="authenticity_token" value="<%= form_authenticity_token %>">
										<input type="hidden" name="post_id" value="<%= post.id %>">
										<input type="hidden" name="back" value="<%= request.url %>">
										<input type="submit" class="button_unlike" value="">
									</form>
								</div> 								
								
								<!-- LIKE BUTTON -->
								<div class="float_left">
									<form action="<%= like_url %>" method="post" data-id="<%= post.id %>" class="grey_unlike_button<%= grey_heart %>">
										<input type="hidden" name="authenticity_token" value="<%= form_authenticity_token %>">
										<input type="hidden" name="post_id" value="<%= post.id %>">
										<input type="hidden" name="back" value="<%= request.url %>">
										<input type="submit" class="button_like" value="">
									</form>
								</div>

						<% else %>
						
							<% if post.draft %>
								<!-- PUBLISH BUTTON -->
								<div class="float_left">
									<a class="button_publish" href="<%= publish_url(post.id) %>" data-id="<%= post.id %>">Publish</a>
								</div>
							<% end %>
						
							<div class="relative">
								<button class="button_options" data-id="<%= post.id %>"></button>
								<div class="options_menu hidden" data-id="<%= post.id %>">
									<div class="selector_top_white"></div>
									
									<!-- EDIT BUTTON -->
									<a class="option_menu_list_item" href="<%= edit_post_url(post.id) %>" data-id="<%= post.id %>">Edit</a>
				
									<!-- DELETE BUTTON -->
									<form action="<%= post_url(post.id) %>" method="post" data-id="<%= post.id %>" data-draft="<%= post.draft %>" class="options_delete_button">
										<input type="hidden" name="_method" value="delete">
										<input type="hidden" name="authenticity_token" value="<%= form_authenticity_token %>">
										<input type="hidden" name="back" value="<%= request.url %>">
										<input class="option_menu_list_item" type="submit" value="Delete">
									</form>
									
								</div>
							</div>
						
						<% end %>
					
					
					</div>
				</div>
				
				</div>
				
			</li>
		<% end %>
	</ul>
		
<% end %>

app/views/posts/drafts.html.erb
<div class="relative"><div class="post_avatar_top"><div class="selector_left"></div></div></div>

<%= render 'posts/new_post_menu' %>

<%= render 'posts/post_items' %>

app/views/posts/edit.html.erb
<div class="relative"><div class="post_my_avatar" style="top: 1px"><div class="selector_left"></div></div></div>

<div class="new_post_container">
	
	<div class="new_post_top_info"><%= current_user.username %></div>

	<form class="new_post_form" action="<%= post_url(@post.id) %>" method="post">
		<input type="hidden" name="authenticity_token" value="<%= form_authenticity_token %>">
		<input type="hidden" name="_method" value="put">
		<input type="hidden" name="back" value="<%= @referer ||= request.referer %>">
	
		<input type="text" name="post[title]" value="<%= @post.title %>" placeholder="Title">
		
		<div class="html_tags_bar">
			<div class="tags_bar_el tag_bold"></div>
			<div class="tags_bar_el tag_italic"></div>
			<div class="tags_bar_el tag_link"></div>
		</div>
	
		<textarea name="post[body]" placeholder="Body"><%= @post.body %></textarea>
	
		<div style="height: 30px">
			<div class="new_post_form_checkbox">
				<input type="checkbox" name="post[draft]" value="true" <%= "checked" if @post.draft %>>
			</div>
			<div class="word_draft_center">Draft</div>

			<% if flash.now[:errors] %>
				<% history = [] %>
				<% flash.now[:errors].each do |key, val| %>
					<% unless history.include?(key) %>
						<div class="new_post_error"><%= key.capitalize %> <%= val.first %></div>
						<% break %>
						<% history << key %>
					<% end %>
				<% end %>
			<% end %>
			<div class="clearfix"></div>
		</div>

		<div>
			<div class="float_left">
				<input type="submit" value="Save">
			</div>
			<div>
				<a class="float_right new_post_cancel" href="<%= @referer ||= request.referer %>">Cancel</a>
			</div>
		</div>
		
	</form>

</div>

app/views/posts/index.html.erb
<div class="relative"><div class="post_avatar_top"><div class="selector_left"></div></div></div>

<%= render 'posts/new_post_menu' %>

<%= render 'posts/post_items' %>

app/views/posts/new.html.erb
<div class="relative"><div class="post_my_avatar" style="top: 1px"><div class="selector_left"></div></div></div>

<div class="new_post_container">
	
	<div class="new_post_top_info"><%= current_user.username %></div>

	<form class="new_post_form" action="<%= posts_url %>" method="post">
		<input type="hidden" name="authenticity_token" value="<%= form_authenticity_token %>">
		<input type="hidden" name="back" value="<%= @referer ||= request.referer %>">
	
		<input type="text" name="post[title]" value="<%= @post.title %>" placeholder="Title">
	
		<div class="html_tags_bar">
			<div class="tags_bar_el tag_bold"></div>
			<div class="tags_bar_el tag_italic"></div>
			<div class="tags_bar_el tag_link"></div>
		</div>
		
		<textarea name="post[body]" placeholder="Body"><%= @post.body %></textarea>
	
		<div style="height: 30px">
			<div class="new_post_form_checkbox">
				<input type="checkbox" name="post[draft]" value="true">
			</div>
			<div class="word_draft_center">Draft</div>
	
			<% if flash.now[:errors] %>
				<% history = [] %>
				<% flash.now[:errors].each do |key, val| %>
					<% unless history.include?(key) %>
						<div class="new_post_error"><%= key.capitalize %> <%= val.first %></div>
						<% break %>
						<% history << key %>
					<% end %>
				<% end %>
			<% end %>
			<div class="clearfix"></div>
		</div>
		
		<div>
			<div class="float_left">
				<input type="submit" value="Post">
			</div>
			<div>
				<a class="float_right new_post_cancel" href="<%= @referer ||= request.referer %>">Cancel</a>
			</div>
		</div>
		
	</form>

</div>